# Generated by Django 5.0.6 on 2024-10-16 12:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('key', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VirtualTryOn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_image_url', models.ImageField(upload_to='cloth')),
                ('full_body_image', models.ImageField(upload_to='bodyimage/')),
                ('output_image', models.ImageField(blank=True, null=True, upload_to='output/')),
                ('type', models.CharField(default='upper', max_length=255)),
                ('version', models.CharField(default='v1', max_length=255)),
                ('message_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
