# Generated by Django 5.1.2 on 2024-10-18 15:55

import home.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('key', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VirtualTryOn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_image_url', models.ImageField(upload_to=home.models.ClothPath())),
                ('full_body_image', models.ImageField(upload_to=home.models.BodyPath())),
                ('output_image', models.ImageField(blank=True, null=True, upload_to=home.models.OutputPath())),
                ('type', models.CharField(default='upper', max_length=255)),
                ('userid', models.CharField(default='default', max_length=255)),
                ('version', models.CharField(default='v1', max_length=255)),
                ('message_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
