# Generated by Django 5.0.6 on 2024-06-12 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_virtualtryon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualtryon',
            name='product_image_url',
            field=models.ImageField(upload_to='cloth'),
        ),
    ]
