# Generated by Django 5.0.6 on 2024-06-12 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_virtualtryon_product_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopifystoredetails',
            name='shop_logo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
